### ISSUE TITLE
_INTERP3 only calls two functions, not three.

### ISSUE THREAD

**Issue by lfnoise** [snej/tails#5]
This looks like a bug. _INTERP2 calls twice, _INTERP3 calls twice also, _INTERP4 calls 4 times.
BTW, I love this idea for implementing threading and want to use it in a synth language. I am the author of the Supercollider audio programming language. Great work.

```
// Interprets 2 following words (saving an instruction and some clock cycles.)
    NATIVE_WORD(_INTERP2, "_INTERP2", StackEffect::weird(),
                Word::MagicWordParam, 2)
    {
        sp = call(sp, (pc++)->word);
        sp = call(sp, (pc++)->word);
        NEXT();
    }

    // Interprets 3 following words.
    NATIVE_WORD(_INTERP3, "_INTERP3", StackEffect::weird(),
                Word::MagicWordParam, 3)
    {
        sp = call(sp, (pc++)->word);
        sp = call(sp, (pc++)->word);
        NEXT();
    }

    // Interprets 4 following words.
    NATIVE_WORD(_INTERP4, "_INTERP4", StackEffect::weird(),
                Word::MagicWordParam, 4)
    {
        sp = call(sp, (pc++)->word);
        sp = call(sp, (pc++)->word);
        sp = call(sp, (pc++)->word);
        sp = call(sp, (pc++)->word);
        NEXT();
    }
```

**Comment by snej** [comment]
Oops! That instruction must not’ve been used anywhere. I’ve pushed a quick fix.

I’d love for Tails (or at least pieces of it) to be used in a ‘real’ project. I’m definitely aware of Supercollider, though I haven’t used it; I’m a musician but I mostly play guitar and dabble in hardware synths.
